
export const ERROR_RECEIVE_ORDER = 'ERROR_RECEIVE_ORDER';
export const REQUEST_ORDER = 'REQUEST_ORDER';
export const RECEIVE_ORDER = 'RECEIVE_ORDER';

export const ERROR_CREATE_ORDER = 'ERROR_ADD_ORDER';
export const REQUEST_CREATE_ORDER = 'REQUEST_ADD_ORDER';
export const RESPONSE_CREATE_ORDER = 'RESPONSE_ADD_ORDER';

export const ERROR_UPDATE_ORDER = 'ERROR_UPDATE_ORDER';
export const REQUEST_UPDATE_ORDER = 'REQUEST_UPDATE_ORDER';
export const RESPONSE_UPDATE_ORDER = 'RESPONSE_UPDATE_ORDER';

