export const ENABLE_SEE_SECRET_PAGE = 'ENABLE_SEE_SECRET_PAGE';
export const ENABLE_SEE_ORDER_PAGE = 'ENABLE_SEE_ORDER_PAGE';
export const ENABLE_SEE_ORDER_DETAILS_PAGE = 'ENABLE_SEE_ORDER_DETAILS_PAGE';
