// Orders
export const ERROR_RECEIVE_ORDERS = 'ERROR_RECEIVE_ORDERS';
export const ERROR_RECEIVE_ORDER = 'ERROR_RECEIVE_ORDER';
export const REQUEST_ORDERS = 'REQUEST_ORDERS';
export const REQUEST_ORDER = 'REQUEST_ORDER';
export const RECEIVE_ORDERS = 'RECEIVE_ORDERS';
export const RECEIVE_ORDER = 'RECEIVE_ORDER';
export const ERROR_DELETE_ORDER = 'ERROR_DELETE_ORDER';
export const REQUEST_DELETE_ORDER = 'REQUEST_DELETE_ORDER';
export const RECEIVE_DELETE_ORDER = 'RECEIVE_DELETE_ORDER';
export const ERROR_ADD_ORDER = 'ERROR_ADD_ORDER';
export const REQUEST_ADD_ORDER = 'REQUEST_ADD_ORDER';
export const RESPONSE_ADD_ORDER = 'RESPONSE_ADD_ORDER';
