export const ERROR_RECEIVE_ORDER_LIST = 'ERROR_RECEIVE_ORDER_LIST';
export const REQUEST_ORDER_LIST = 'REQUEST_ORDER_LIST';
export const RECEIVE_ORDER_LIST = 'RECEIVE_ORDER_LIST';

export const ERROR_DELETE_ORDER = 'ERROR_DELETE_ORDER';
export const REQUEST_DELETE_ORDER = 'REQUEST_DELETE_ORDER';
export const RECEIVE_DELETE_ORDER = 'RECEIVE_DELETE_ORDER';

